version: "3"
networks:
  net-etcd:

services:
  etcd1:
    env_file: envs/etcd1.env
    image: ${image}
    container_name: ${node_name}
    command: etcd -name ${node_name} -advertise-client-urls ${advertise-client-urls} -listen-client-urls ${listen-client-urls} -listen-peer-urls ${listen-peer-urls} -initial-cluster-token ${initial-cluster-token} -initial-cluster ${initial-cluster} -initial-cluster-state ${initial-cluster-state}
    ports:
      - 12379:2379
      - 12380:2380
    volumes:
      - /data/${node_name}:/data
    restart: on-failure
    networks:
      - net-etcd

  etcd2:
    env_file: envs/etcd2.env
    image: ${image}
    container_name: ${node_name}
    command: etcd -name ${node_name} -advertise-client-urls ${advertise-client-urls} -listen-client-urls ${listen-client-urls} -listen-peer-urls ${listen-peer-urls} -initial-cluster-token ${initial-cluster-token} -initial-cluster ${initial-cluster} -initial-cluster-state ${initial-cluster-state}
    ports:
      - 12378:2379
      - 12381:2380
    volumes:
      - /data/${node_name}:/data
    restart: on-failure
    networks:
      - net-etcd

  etcd3:
    env_file: envs/etcd3.env
    image: ${image}
    container_name: ${node_name}
    command: etcd -name ${node_name} -advertise-client-urls ${advertise-client-urls} -listen-client-urls ${listen-client-urls} -listen-peer-urls ${listen-peer-urls} -initial-cluster-token ${initial-cluster-token} -initial-cluster ${initial-cluster} -initial-cluster-state ${initial-cluster-state}
    ports:
      - 12377:2379
      - 12382:2380
    volumes:
      - /data/${node_name}:/data
    restart: on-failure
    networks:
      - net-etcd
