version: "3"
networks:
  net-etcd:

services:
  etcd1:
    env_file: envs/etcd1.env
    image: ${image}
    container_name: etcd1
    command: etcd -name ${node_name} -advertise-client-urls ${advertise_client_urls} -listen-client-urls ${listen_client_urls} -listen-peer-urls ${listen_peer_urls} -initial-cluster-token ${initial_cluster_token} -initial-cluster ${initial_cluster} -initial-cluster-state ${initial_cluster_state}
    ports:
      - 12379:2379
      - 12380:2380
    volumes:
      - /data/etcd1:/data
    restart: on-failure
    networks:
      - net-etcd

  etcd2:
    env_file: envs/etcd2.env
    image: ${image}
    container_name: etcd2
    command: etcd -name ${node_name} -advertise-client-urls ${advertise_client_urls} -listen-client-urls ${listen_client_urls} -listen-peer-urls ${listen_peer_urls} -initial-cluster-token ${initial_cluster_token} -initial-cluster ${initial_cluster} -initial-cluster-state ${initial_cluster_state}
    ports:
      - 12378:2379
      - 12381:2380
    volumes:
      - /data/etcd2:/data
    restart: on-failure
    networks:
      - net-etcd

  etcd3:
    env_file: envs/etcd3.env
    image: ${image}
    container_name: etcd3
    command: etcd -name ${node_name} -advertise-client-urls ${advertise_client_urls} -listen-client-urls ${listen_client_urls} -listen-peer-urls ${listen_peer_urls} -initial-cluster-token ${initial_cluster_token} -initial-cluster ${initial_cluster} -initial-cluster-state ${initial_cluster_state}
    ports:
      - 12377:2379
      - 12382:2380
    volumes:
      - /data/etcd3:/data
    restart: on-failure
    networks:
      - net-etcd
