version: "3"
# 网络
networks:
  net-consul:

services:
  consul1:
    env_file: envs/node1.env
    image: ${image}
    container_name: node1
    command: agent -server ${args} -node=node1 -bind=${bind_address} -client=${client} -datacenter=${datacenter}
    ports:
      # http
      - 18501:8500
      # rpc
      - 18301:8300
    volumes:
      - /data/consul/node1:/consul/data
    restart: on-failure
    networks:
      - net-consul

  consul2:
    env_file: envs/node2.env
    image: ${image}
    container_name: node2
    command: agent -server ${args} -node=node2 -bind=${bind_address} -client=${client} -datacenter=${datacenter}
    ports:
      # http
      - 18502:8500
      # rpc
      - 18302:8300
    volumes:
      - /data/consul/node2:/consul/data
    restart: on-failure
    depends_on:
      - consul1
    networks:
      - net-consul

  consul3:
    env_file: envs/node3.env
    image: ${image}
    container_name: node3
    command: agent -server ${args} -node=node3 -bind=${bind_address} -client=${client} -datacenter=${datacenter}
    ports:
      # http
      - 18503:8500
      # rpc
      - 18303:8300
    volumes:
      - /data/consul/node3:/consul/data
    restart: on-failure
    depends_on:
      - consul1
    networks:
      - net-consul

  consul4:
    image: ${image}
    env_file: envs/node4.env
    container_name: node4
    command: agent -server ${args} -node=node4 -bind=${bind_address} -client=${client} -datacenter=${datacenter}
    ports:
      # http
      - 18500:8500
      # rpc
      - 18300:8300
    volumes:
      - /data/consul/node4:/consul/data
    restart: on-failure
    depends_on:
      - consul2
      - consul3
    networks:
      - net-consul
