version: "3"

services:
  showDoc:
    image: star7th/showdoc
    container_name: showDoc
    ports:
      - ${http_service_port}:80
      - ${https_service_port}:443
      - ${ldap_service_port}:9000
    volumes:
      - ${html_dir}:/var/www/html/
    restart: always
    user: ${user_name}
    privileged: true
